### ISSUE TITLE
make bottomContent configurable

### ISSUE THREAD

**Issue by sramam** [mokkabonna/inquirer-autocomplete-prompt#102]
It'd be really useful to make the [bottomContent configurable](https://github.com/mokkabonna/inquirer-autocomplete-prompt/blob/47a42bc2335b90c03b09402b3a7753a6a67251c2/index.js#L101).

It'll allow for a much better user experience - providing pertinent feedback on what to do to fix the "no results" case, since that varies by prompt.

**Comment by mokkabonna** [comment]
This is fixed. You can now specify that text and the search text in the options. See the README.md
