### ISSUE TITLE
Is it possible to multiple-select?

### ISSUE THREAD

**Issue by matheo** [mokkabonna/inquirer-autocomplete-prompt#104]
I was wondering if this prompt can allow multiple options to be selected
I don't see a mention in the docs about this.

Thanks for this great autocompleter!

**Comment by mokkabonna** [comment]
No, and I'm not sure I want to add it.

It would be simple enough if all the items you want to select are on the same page. But what if you do a search, select one item, do another search, select one more. Now you need a way to see all selected for instance. Would be much more complex. 

I try to mimic the list prompt, not the checkbox prompt.
