### ISSUE TITLE
Would it be possible to add a "default" option? Would you be open to a PR?

### ISSUE THREAD

**Issue by shanebdavis** [mokkabonna/inquirer-autocomplete-prompt#108]
I'd really like to specify the default when using this module. All I want is the cursor to start on the item who's string matches the default value, if specified.

I'm willing to do the work and create a PR if you are open to this extention.

**Comment by mokkabonna** [comment]
Will be resolved when #114 is completed.

**Comment by mokkabonna** [comment]
Released with version v1.2.0
