### ISSUE TITLE
TypeError: this.line.substring is not a function

### ISSUE THREAD

**Issue by ElvisWong** [mokkabonna/inquirer-autocomplete-prompt#129]
It crashes when I tab on "Tab" button for autocomplete. This is how I works with inquirer modules.

```
await inquirer.prompt([
  {
      type: "autocomplete",
      name: "product",
      message: `test`,
      suggestOnly: true,
      source: function (ans, input) {
        return new Promise(async function (res) {
          const search = input
            ? await Product.find({
                name: { $regex: new RegExp(input, `i`) },
              }).lean()
            : [];
          const choices = search.map((x) => ({
            name: x.name,
            value: x,
          }));
          res(choices);
        });
      },
    },
]);
```

![image](https://user-images.githubusercontent.com/9835818/121118651-ce59e680-c84c-11eb-9387-3b4899440018.png)

This error happens when I set value as object to the `source` function. Once I changed back the value to string, It works fine.

**Comment by mokkabonna** [comment]
I can no longer reproduce this. Keep in mind also that with suggestonly it is basically a regular text input. So if you have an object there that is not really supported.
