### ISSUE TITLE
No reaction on Windows 10 console.

### ISSUE THREAD

**Issue by alinnert** [mokkabonna/inquirer-autocomplete-prompt#13]
Hi,

I'm really interested in this plugin. I also just discovered inquirer, so I'm not very experienced with it.
I do know that the question type "list" works fine. But autocomplete doesn't show any reaction. I can't input any text nor can I select values from the list. The initial content of the list works fine though.

I've created this little test script:

``` javascript
'use strict';

const inquirer = require('inquirer');
inquirer.registerPrompt('autocomplete', require('inquirer-autocomplete-prompt'));

inquirer.prompt([
    {
        type: 'autocomplete',
        name: 'first',
        message: 'What do you want to do?',
        source: (answers, input) => {
            return new Promise((resolve, reject) => {
                resolve([input + ' 1', input + ' 2', input + ' 3']);
            });
        }
    }
], answers => {
    console.log(JSON.stringify(answers));
});
```

When I start it I get the output, which is fine obviously:

```
? What do you want to do? (Use arrow keys or type to search)
> null 1
  null 2
  null 3
```

But after showing the question the script basically "freezes". I can accept the first entry with `enter` or stop it with `Ctrl` + `C`.

**Comment by SBoudrias** [comment]
Make sure you're on the latest Node version. There was a bug on Windows.

**Comment by alinnert** [comment]
Okay, I forgot to mention. I'm using Node 5.4.0. So, latest version.

**Comment by Blahah** [comment]
I get the same on OSX, node `5.5.0`, inquirer-autocomplete-prompt 0.1.3

When the search prompt is shown I can type but the typed letters don't appear. If I hit enter the search runs and the typed letters appear next to the prompt. Arrow keys don't work, and enter chooses the first result.

**Comment by devinus** [comment]
Same issue as @Blahah

**Comment by mokkabonna** [comment]
Checked this now on windows 10 with node 6.9.5 LTS. It works mostly as expected, some sligh visual problem.
