### ISSUE TITLE
Supporting the name, value, short schema

### ISSUE THREAD

**Issue by ckosmowski** [mokkabonna/inquirer-autocomplete-prompt#142]
Often for lists and choices inquirer supports objects containing name, value and short properties for display, resulting value and displayed short value after selection.

It seems like autocomplete only accepts strings currently. I'd like to request the above as a feature.

**Comment by mokkabonna** [comment]
This should work, tested it now. What are you doing? 

`js
const choicesFull = [
  {
    name: 'Apple',
    value: 'apple-value',
    short: 'apple-short',
  },
];

inquirer
  .prompt([
    {
      type: 'autocomplete',
      name: 'fruit',
      suggestOnly: true,
      message: 'What is your favorite fruit?',
      searchText: 'We are searching the internet for you!',
      emptyText: 'Nothing found!',
      default: 'Banana',
      source: async () => choicesFull,
      pageSize: 4,
    },
])
`
