### ISSUE TITLE
Does not work with inquirer.createPromptModule

### ISSUE THREAD

**Issue by sargunv** [mokkabonna/inquirer-autocomplete-prompt#146]
### Environment

* inquirer 8.2.4
* inquirer-autocomplete-prompt 2.0.0
* node 16.16.0
* VSCode terminal on macOS 

### Symptom

The choices don't show up for selection when using this package with `inquirer.createPromptModule`. This means it's not possible to use this package while outputting to stderr instead of stdout. Standard inquirer types work fine (such as `list`, the closest equivalent to this available).

<img width="301" alt="CleanShot 2022-10-20 at 12 46 29@2x" src="https://user-images.githubusercontent.com/1320357/197009513-329bba16-be99-4ae9-a9a7-7294469d6de0.png">

### Repro

```js
const inqurier = require("inquirer");
inquirer.registerPrompt('autocomplete', require('inquirer-autocomplete-prompt'));

// works
inquirer.prompt({ 'type': 'autocomplete', ... })

// does not work
const prompt1 = inquirer.createPromptModule({ output: stderr });
prompt1({ 'type': 'autocomplete', ... })

// also does not work
const prompt2 = inquirer.createPromptModule({});
prompt2({ 'type': 'autocomplete', ... })

// builtin list type works fine still
prompt1({ 'type': 'list', ... })
prompt2({ 'type': 'list', ... })
```

**Comment by mokkabonna** [comment]
As I understand createPromptModule is that is is separate from the default inquirer. 

So you have to register the autocomplete prompt with the prompt1 or prompt2 module. 
See https://github.com/mokkabonna/inquirer-autocomplete-prompt/commit/3ee49870b82f3fad10f98c704839cf4b819f273a

**Comment by mokkabonna** [comment]
Yeah sorry for the late reply.  :)
