### ISSUE TITLE
Feature Request: support multiple choices

### ISSUE THREAD

**Issue by yangchenyun** [mokkabonna/inquirer-autocomplete-prompt#15]
It is common to select multiple items in 'choices'; an idea will be to modify the 'onSubmit' callback and distinguish between an action to pick current selected item and an action to continue to next prompt.

**Comment by mokkabonna** [comment]
This is better solved by a separate plugin

**Comment by whitecolor** [comment]
@mokkabonna I wonder why, what is the problem of adding ability to do multiple choises?

**Comment by whitecolor** [comment]
Well I thought and it is probably really not so needed, you may implement multiple choises by asking multiple times to choose from autocomplete list, and in most scenarios it would be more appropriate then to choose from autocomplte matched options.

Though there maybe some cases for example implementing what files should be added to git stage/commit.
