### ISSUE TITLE
Display cursor when typing

### ISSUE THREAD

**Issue by mdashlw** [mokkabonna/inquirer-autocomplete-prompt#154]
The standalone version no longer shows cursor when typing while allowing to move it with arrow keys which is rather inconvenient. It'd be nice to have the cursor back

**Comment by mokkabonna** [comment]
Thanks for reporting, should be fixed in 0.6.0

Be aware though that as indicated by the versioning here (less than 1) it is still considered not 100% done necessarily. I have yet to test properly the dual export cjs and esm modules.
