### ISSUE TITLE
Need rename `lib` to `src` inquirer@9.3.2

### ISSUE THREAD

**Issue by deot** [mokkabonna/inquirer-autocomplete-prompt#159]
https://github.com/SBoudrias/Inquirer.js/pull/1449
Renames:
- `lib` to `src`
- root to `index.js`

https://github.com/mokkabonna/inquirer-autocomplete-prompt/blob/55a41fddf02dd0dbc9f32ba77878b191cc303c5a/packages/inquirer-autocomplete-prompt/index.js#L9

**Comment by Choppel** [comment]
As mentioned in issue #1456 of inquirer, the imports do not work as expected anymore, because the internal file structure has changed. @SBoudrias states, that the way of importing is not the one that is documented.

Something like 
```
import inquirer from 'inquirer'; 

type Base = inquirer.prompts.PromptBase;
```
should be correct.

**Comment by SySagar** [comment]
Have been facing this issue in my js-based-terminal since yesterday. Traced back to this repo to know the real issue. Can you suggest what should we do for now? is there any alternative?

**Comment by Choppel** [comment]
Downgrading and freezing inquirer to 9.3.1 works for me.
```
"dependencies": {
  "inquirer": "9.3.1"
}
```

**Comment by SBoudrias** [comment]
`inquirer@9.3.3` should have fixed the issues with plugins 🤞🏻
