### ISSUE TITLE
Feature Request: Support initial search text

### ISSUE THREAD

**Issue by tjbenton** [mokkabonna/inquirer-autocomplete-prompt#18]
I'm currently using a command line api that allows you to pass in a `name` to identify which projected the user wants to compile, and if the user passes is `s` as their `name` argument it's not going to match anything in the exactly but it would reduce the initial list that's displayed if I could pass in an `initial` option that would be the first thing passed into the `source` function instead of `null`

Here's some screenshots of what I'm talking about.

Currently this is what's happening. If the user passes in a name that's not an exact match my app will return throw that warning and run the auto complete prompt, and the list is untouched.

![current](https://cloud.githubusercontent.com/assets/4776422/20070313/ea7d181e-a4ed-11e6-8bdc-940f997c1d3c.png)

Here's what I would like it to look like if there was a initial search term. Where the initial search term was `s` and it shows the matched results based off of `s`. 

![proposed](https://cloud.githubusercontent.com/assets/4776422/20070812/de81e3e4-a4ef-11e6-94f5-6a8b466d4165.png)

**Comment by mokkabonna** [comment]
See comment on linked PR
