### ISSUE TITLE
`pageSize` option is not always followed when specified

### ISSUE THREAD

**Issue by sindresorhus** [mokkabonna/inquirer-autocomplete-prompt#23]
Here, I have set `pageSize` to `10`, but it's showing more than 10 results. Interestingly, this doesn't happen on the first search character, in this case `s`.

If I don't specify `pageSize`, everything works perfectly.

<img width="324" alt="screen shot 2017-02-27 at 10 41 44" src="https://cloud.githubusercontent.com/assets/170270/23348053/6cdf186e-fcd9-11e6-8639-20c3eb462122.png">

**Comment by mokkabonna** [comment]
That is weird. I can't reproduce it on my system. Node 6.9.6, ubuntu 14.04 (elementary os).

Does it happen with any pageSize?

**Comment by mokkabonna** [comment]
I was able to reproduce it finally, however not with as many extra as you had. I was able to reproduce it with 2 more than the pageSize. And that is due to this: https://github.com/SBoudrias/Inquirer.js/blob/master/lib/utils/paginator.js#L22

**Comment by mokkabonna** [comment]
Try it again with the lastest version, fixed in inquirer.

**Comment by sindresorhus** [comment]
Works great. Thanks for fixing :)
