### ISSUE TITLE
Filter is not applied to answer

### ISSUE THREAD

**Issue by brandonjpierce** [mokkabonna/inquirer-autocomplete-prompt#31]
`filter` is not applied to the selected value / answer. To reproduce adjust your `example.js` file prompts to:

```javascript
{
  type: 'autocomplete',
  name: 'fruit',
  suggestOnly: true,
  message: 'What is your favorite fruit?',
  source: searchFood,
  pageSize: 4,
  filter: answer => answer.slice(0, 2),
  validate: function(val) {
    return val ? true : 'Type something!';
  },
}, {
  type: 'autocomplete',
  name: 'state',
  message: 'Select a state to travel from',
  source: searchStates,
  filter: answer => answer.slice(0, 2),
},
```

Notice the values remain unchained.

**Comment by mokkabonna** [comment]
Thanks for reporting, is fixed in latest release 0.9.0

https://github.com/mokkabonna/inquirer-autocomplete-prompt/commit/59b29e7e060a8aa6599481a907b6fc582e7d5676

**Comment by mokkabonna** [comment]
Currently only synchronous filter is implemented

**Comment by brandonjpierce** [comment]
Excellent, thanks so much!

**Comment by mokkabonna** [comment]
Have now implemented async filter as well. 0.10.0
