### ISSUE TITLE
Filter value not applied to UI

### ISSUE THREAD

**Issue by brandonjpierce** [mokkabonna/inquirer-autocomplete-prompt#32]
Hello, me again :D

So the recent filter update you made works great, thanks again for adding that! In default `inquirer` prompts, if you supply a filter, that filter value will become the answer in the UI. 

I've provided a gif to make it easier to explain what I mean. Notice the default `input` type prompt's display answer is converted to `ab` even though `abc123` was entered. However in the autocomplete `prompt` the answer value is not changed even though a filter is supplied. The filter for both prompts is simply: `answer.slice(0, 2)`.

![autocomplete-bug](https://user-images.githubusercontent.com/5483779/27512576-ea478a56-590a-11e7-81ed-6164da7477d6.gif)

**Comment by mokkabonna** [comment]
Try lastest release 0.11.0, it should behave like the normal text input in this regard.

**Comment by brandonjpierce** [comment]
Seems to work yes but in my case I have `suggestOnly` set to `false`. I feel like the UI should render the filtered value regardless. Was there a particular reason behind putting it behind the `suggestOnly` conditional?

**Comment by mokkabonna** [comment]
I saw your comment on email. The reason for putting it behind the flag is because in suggestOnly mode it behaves like the input prompt. With the flag off it behaves like the list prompt. And the list prompt does not apply the filter for the ui.

But maybe you saw that and deleted the comment?

**Comment by brandonjpierce** [comment]
@mokkabonna Yeah I misunderstood the default behavior of inquirer, your implementation of filtering the value when in `suggestOnly` mode is correct!
