### ISSUE TITLE
How add in Yeoman ?

### ISSUE THREAD

**Issue by brunoosilva** [mokkabonna/inquirer-autocomplete-prompt#35]
Hello, 

How add in Yeoman ?

Thank you

**Comment by mokkabonna** [comment]
Not exactly sure, but have you tried registering it and then just use it?

```
inquirer.registerPrompt('autocomplete', require('inquirer-autocomplete-prompt'));
```

**Comment by brunoosilva** [comment]
Thanks for your answer..

Inside the Yeoman Generator, don't have access the variable **inquirer**, because is a internal dependence of Yeoman. How register this plugin ?

**Comment by SBoudrias** [comment]
@brunoosilva that's not really possible because Yeoman is a generic interface integrated in a few differents tools (there's `yo`, but also the GUI implementations/integrations). If you don't use the default, then the GUI won't know how to get an answer to the prompts.

**Comment by ruslangallo** [comment]
@brunoosilva look at this:
https://github.com/diegohaz/arc/blob/generator-arc/src/store/index.js

**Comment by mokkabonna** [comment]
Thanks @ruslankhh

**Comment by dhruvdutt** [comment]
@mokkabonna Did it work?
