### ISSUE TITLE
validate value is empty

### ISSUE THREAD

**Issue by andykais** [mokkabonna/inquirer-autocomplete-prompt#40]
```
{
    type: 'autocomplete',
    name: 'name',
    message: 'which do you choose?',
    source: (answersSoFar, input) => search(input),
    suggestOnly: true,
    validate: value => console.log(value)
}
```
using
```
    "inquirer-autocomplete-prompt": "^0.11.0",
```
value passed to validate is empty, search is async.

It would also be nice if I could validate an input even when suggestOnly is false. There are times when I want to check async things and the validate step is the most appropriate place to do it.

**Comment by mokkabonna** [comment]
This seems to be working fine in the example.js 

As for introducing validate when suggestOnly false I don't think I want to introduce that. I want to mimic as much as possible the list input in inquirer. It does not have the validate method. You should rather make sure in "search" that only valid options a provided.
