### ISSUE TITLE
No multi-item autocomplete

### ISSUE THREAD

**Issue by smanwaring** [mokkabonna/inquirer-autocomplete-prompt#50]
I don't see a way to autocomplete multiple items. For instance, if I wanted a user to be able to tab-autocomplete multiple inputs on the same line, each separated by a comma (e.g.,`my-selection-1, my-selection-2`). 

Is this a feature that is going to be added in the future?

**Comment by mokkabonna** [comment]
I don't think that's something I want to add to this library. I suspect the rendering of that would be difficult.

Probably best created as a standalone prompt. Maybe with this library as a base. I personally don't have the time/interest to do that, but maybe someone want to fork this and add the functionality.
