### ISSUE TITLE
Add inquirer as peer dependency

### ISSUE THREAD

**Issue by dhruvdutt** [mokkabonna/inquirer-autocomplete-prompt#53]
Why don't we mention `inquirer` as a peer dependency in this project rather than using it as a dependency?

Also, can we upgrade inquirer to version [`5.1.0`](https://www.npmjs.com/package/inquirer)

**Comment by karlhorky** [comment]
Inquirer.js has been upgraded to 6.0.0 in inquirer-autocomplete-prompt@1.0.0.

**Comment by karlhorky** [comment]
Published in inquirer-autocomplete-prompt@1.0.1
