### ISSUE TITLE
please add prefix and suffix in base.js file.

### ISSUE THREAD

**Issue by kul2789** [mokkabonna/inquirer-autocomplete-prompt#58]
Hello mokkabonna 
i am using this module and found an issue. Prefix and suffix is missing from base.js file. i am using inquirer which is supporting prefix and suffix and was presuming that this module is using inquirer as it is as dependency but i was wrong i have gone through the files and manually added prefix and suffix in my local node_module.
```
this.opt = _.defaults(_.clone(question), {
    validate: function () {
      return true;
    },
    filter: function (val) {
      return val;
    },
    when: function () {
      return true;
    },
    suffix: '',
    prefix: chalk.green('?')
 });

```

```
Prompt.prototype.getQuestion = function () {
  var message = this.opt.prefix + ' ' + chalk.bold(this.opt.message)  + this.opt.suffix + chalk.reset(' ');
.......
}
```

**Comment by mokkabonna** [comment]
I have testet now that prefix and suffix work as intended with inquirer 8.
