### ISSUE TITLE
Accept arbitrary string as input?

### ISSUE THREAD

**Issue by mhkeller** [mokkabonna/inquirer-autocomplete-prompt#6]
I'm looking for an inquirer plugin that would present a list as a starting off point but allow for an arbitrary string if the list doesn't have what the user wants. This module looks like a great starting point. Do you have any guidance on where to tweak it for that behavior?

**Comment by mhkeller** [comment]
This seems to be working. Did I miss anything? https://github.com/mhkeller/inquirer-autocomplete-prompt/commit/38c0f0abce15ca9c4297a5b9a78cf7c0b9a6b8cf

**Comment by mokkabonna** [comment]
That was my thought as well. As you noticed this plugin currently forces you to choose a predefined one. But also see the usefulness of being able to type anything you want. Was eventually planning to either support it with an option or create a stand alone one. 

But don't know when I'll have the time to complete that, so if you create it, that is great!

That looks like the gist of it, although with your changes it seems that you only will be able to select something custom when it does not match anything. so you will not be able to enter "cookie" as a value if you have "cookie monster" in the list. Correct?

**Comment by mhkeller** [comment]
Ah ya I hadn't thought of that one. There might need to be a larger UI change in order to disambiguate when you want "cookie" to autocomplete to "Cookie Monster". 

I don't have that use case currently.  so for now I'll look at integrating this set up as an option and PR.

**Comment by mhkeller** [comment]
I didn't see your flow layout above when I read this on my phone. Ya that seems reasonable although would "cookie monster" appear selected in the list after typing "cookie" before hitting tab? 

Another way to do it is always display the arbitrary input in the list and preface it with some text or in a different style so the user knows it is not a part of the main list.

**Comment by Naramsim** [comment]
@mhkeller could you open a PR with your changes? So the users now are not forced to choose one option?

**Comment by Naramsim** [comment]
Or this PR does the same?
https://github.com/mokkabonna/inquirer-autocomplete-prompt/pull/9

**Comment by mokkabonna** [comment]
Closed in favor of #9 . It is now merged and published.
