### ISSUE TITLE
Is it possible to create a typings file for use in Typescript?

### ISSUE THREAD

**Issue by roybass** [mokkabonna/inquirer-autocomplete-prompt#61]
Please create a typings file so Typescript users could enjoy this package.
Thanks :)

**Comment by pferreir** [comment]
I'm just using this:

```js
declare module "inquirer-autocomplete-prompt" {
    import { PromptModule } from "inquirer";

    let AutocompletePrompt: PromptModule;
    export = AutocompletePrompt;
}
```

**Comment by roybass** [comment]
Thanks @pferreir!

**Comment by bbernstein** [comment]
Make your own `@types` folder and name the file `inquirer-autocomplete-prompt.d.ts`.
So the path is (relative to your sources): `@types/inquirer-autocomplete-prompt.ts`
