### ISSUE TITLE
inquirer.Separator not being rendered

### ISSUE THREAD

**Issue by erhhung** [mokkabonna/inquirer-autocomplete-prompt#67]
Because of the rotating nature of the selection list, if the list size is greater than `pageSize`, I'd like to put a separator at the end of my list. Adding `new inquirer.Separator()` to the `choices` array works for type "list", but it appears to be omitted in the "autocomplete" version.

**Comment by SurenAt93** [comment]
Is there any update related to this issue?

**Comment by SurenAt93** [comment]
What does this code segment mean?

https://github.com/mokkabonna/inquirer-autocomplete-prompt/blob/master/index.js#L186

**Comment by polygoat** [comment]
+1

**Comment by murac** [comment]
yeah what gives?

**Comment by mokkabonna** [comment]
This is fixed now. https://github.com/mokkabonna/inquirer-autocomplete-prompt/commit/2ac69b951cf9485c44daa428031146ba69ae7edd
