### ISSUE TITLE
Periodic (streamed) updates of  the sugestions

### ISSUE THREAD

**Issue by whitecolor** [mokkabonna/inquirer-autocomplete-prompt#76]
Is it difficult to make source not promise (single resolve) but stream-like, that would allow periodical update of the suggestions without user input?

**Comment by mokkabonna** [comment]
It is possible to maybe implement, but I am curious to your use case. I can't remember any say, web autocomplete, that does this.

A possible solution would be to pass a third argument to the source function that is a function, and calling this would allow you to update the list.

But it would complicate things a bit. So I don't think I would want to add that unless there is several people that request that.

Closing, but comment if anyone has anything to say.
