### ISSUE TITLE
Tab complete throws TypeError exception

### ISSUE THREAD

**Issue by jordanranz** [mokkabonna/inquirer-autocomplete-prompt#81]
Getting the follow exception after attempting to tab complete with `suggestOnly: true`

`TypeError: Cannot read property 'length' of null at InquirerFuzzyPath.Prompt.onKeypress (/Users/jranz/amplify/amplify-cli/packages/amplify-category-xr/node_modules/inquirer-autocomplete-prompt/index.js:221:61) ...`

https://github.com/mokkabonna/inquirer-autocomplete-prompt/blob/master/index.js#L215

Related to: https://github.com/adelsz/inquirer-fuzzy-path/issues/7

**Comment by mokkabonna** [comment]
Don't think it's related to this prompt.
