### ISSUE TITLE
Support for inquirer@7

### ISSUE THREAD

**Issue by rheaditi** [mokkabonna/inquirer-autocomplete-prompt#91]
Hey! 👋
Thanks for building & maintaining `inquirer-autocomplete-prompt`!

We've been using `inquirer-autocomplete-prompt` in our project [ClearTax/pivotal-flow](https://github.com/ClearTax/pivotal-flow) with `inquirer@7.0.0` for a while now without any issues (as per our use case).

Just wondering if there are any plans to support that version officially in `inquirer-autocomplete-prompt` - since it keeps showing peer dependency warnings.

**Comment by mitschmidt** [comment]
Thanks for this great package. Same here - heavily using it with inquirer 7.0.x without any trouble.

**Comment by mokkabonna** [comment]
merged, but not released yet, soon!
